# Generated by Django 4.2.5 on 2023-09-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_experience_job_publish_at_job_salary_job_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cetegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
