# Generated by Django 4.2.5 on 2023-09-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_cetegory_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cetegory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.cetegory'),
            preserve_default=False,
        ),
    ]
