# Generated by Django 4.2.5 on 2023-09-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
