# Generated by Django 4.2.5 on 2023-09-13 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_alter_apply_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cetegory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job.cetegory'),
        ),
    ]
