# Generated by Django 4.2.5 on 2023-09-14 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_apply_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='cv',
        ),
    ]
