# Generated by Django 4.2.5 on 2023-09-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_remove_apply_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='cv',
            field=models.FileField(default='', upload_to='cv/'),
            preserve_default=False,
        ),
    ]
