# Generated by Django 4.2.5 on 2023-09-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
